"""initial schema - 9 core tables

Revision ID: eb7fc4bd2c12
Revises: 
Create Date: 2026-07-16 07:40:39.388480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb7fc4bd2c12'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_registry',
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('algorithm', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('training', 'active', 'inactive', 'archived', name='model_status'), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('roc_auc', sa.Float(), nullable=True),
    sa.Column('pr_auc', sa.Float(), nullable=True),
    sa.Column('training_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dataset_name', sa.String(length=255), nullable=False),
    sa.Column('dataset_row_count', sa.Integer(), nullable=True),
    sa.Column('model_file_path', sa.String(length=500), nullable=True),
    sa.Column('scaler_file_path', sa.String(length=500), nullable=True),
    sa.Column('shap_explainer_file_path', sa.String(length=500), nullable=True),
    sa.Column('hyperparameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_registry_created_at'), 'model_registry', ['created_at'], unique=False)
    op.create_index(op.f('ix_model_registry_id'), 'model_registry', ['id'], unique=False)
    op.create_index('ix_model_registry_single_active', 'model_registry', ['status'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_index(op.f('ix_model_registry_status'), 'model_registry', ['status'], unique=False)
    op.create_index(op.f('ix_model_registry_version'), 'model_registry', ['version'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'analyst', 'auditor', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False, comment='e.g. "LOGIN", "CREATE_TRANSACTION"'),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_endpoint'), 'audit_logs', ['endpoint'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index('ix_audit_logs_user_created_at', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('model_metrics',
    sa.Column('model_registry_id', sa.UUID(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('precision', sa.Float(), nullable=False),
    sa.Column('recall', sa.Float(), nullable=False),
    sa.Column('f1_score', sa.Float(), nullable=False),
    sa.Column('confusion_matrix', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='{"tp": 0, "fp": 0, "tn": 0, "fn": 0}'),
    sa.Column('roc_curve', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='{"fpr": [...], "tpr": [...], "thresholds": [...]}'),
    sa.Column('pr_curve', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='{"precision": [...], "recall": [...], "thresholds": [...]}'),
    sa.Column('avg_latency_ms', sa.Float(), nullable=True),
    sa.Column('prediction_count', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False, comment='When this snapshot was computed — may differ from created_at if backfilled'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_registry_id'], ['model_registry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_metrics_created_at'), 'model_metrics', ['created_at'], unique=False)
    op.create_index(op.f('ix_model_metrics_id'), 'model_metrics', ['id'], unique=False)
    op.create_index('ix_model_metrics_model_recorded_at', 'model_metrics', ['model_registry_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_model_metrics_model_registry_id'), 'model_metrics', ['model_registry_id'], unique=False)
    op.create_index(op.f('ix_model_metrics_recorded_at'), 'model_metrics', ['recorded_at'], unique=False)
    op.create_table('transactions',
    sa.Column('time_feature', sa.Float(), nullable=False, comment="Seconds elapsed, same semantics as the dataset's Time column"),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('v_features', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='PCA components V1..V28, e.g. {"V1": -1.359, ..., "V28": -0.021}'),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('merchant', sa.String(length=255), nullable=True),
    sa.Column('customer_reference', sa.String(length=255), nullable=True),
    sa.Column('card_last4', sa.String(length=4), nullable=True),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('submitted_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_amount'), 'transactions', ['amount'], unique=False)
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_customer_reference'), 'transactions', ['customer_reference'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_merchant'), 'transactions', ['merchant'], unique=False)
    op.create_index('ix_transactions_merchant_created_at', 'transactions', ['merchant', 'created_at'], unique=False)
    op.create_index(op.f('ix_transactions_submitted_by_id'), 'transactions', ['submitted_by_id'], unique=False)
    op.create_table('fraud_logs',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Enum('validation', 'preprocessing', 'prediction', 'decision', 'persistence', 'notification', name='pipeline_stage'), nullable=False),
    sa.Column('status', sa.Enum('success', 'failure', name='log_status'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Stage-specific structured detail, e.g. feature values or error traces'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fraud_logs_created_at'), 'fraud_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_fraud_logs_id'), 'fraud_logs', ['id'], unique=False)
    op.create_index(op.f('ix_fraud_logs_status'), 'fraud_logs', ['status'], unique=False)
    op.create_index(op.f('ix_fraud_logs_transaction_id'), 'fraud_logs', ['transaction_id'], unique=False)
    op.create_index('ix_fraud_logs_transaction_stage', 'fraud_logs', ['transaction_id', 'stage'], unique=False)
    op.create_table('fraud_predictions',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('model_registry_id', sa.UUID(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('is_fraud', sa.Boolean(), nullable=False),
    sa.Column('fraud_probability', sa.Float(), nullable=False, comment='Raw model output, 0.0-1.0'),
    sa.Column('risk_score', sa.Float(), nullable=False, comment='fraud_probability scaled 0-100'),
    sa.Column('confidence', sa.Float(), nullable=False, comment="Model's confidence in this prediction, 0.0-1.0"),
    sa.Column('decision', sa.Enum('approve', 'mfa_required', 'blocked', name='decision'), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False, comment='Inference wall-clock time'),
    sa.Column('top_shap_features', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='[{"feature": "V17", "impact": 0.31, "value": -3.2}, ...] ordered by |impact| desc'),
    sa.Column('explanation', sa.Text(), nullable=False, comment='Natural-language SHAP explanation'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_registry_id'], ['model_registry.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fraud_predictions_created_at'), 'fraud_predictions', ['created_at'], unique=False)
    op.create_index(op.f('ix_fraud_predictions_decision'), 'fraud_predictions', ['decision'], unique=False)
    op.create_index('ix_fraud_predictions_decision_created_at', 'fraud_predictions', ['decision', 'created_at'], unique=False)
    op.create_index(op.f('ix_fraud_predictions_id'), 'fraud_predictions', ['id'], unique=False)
    op.create_index(op.f('ix_fraud_predictions_is_fraud'), 'fraud_predictions', ['is_fraud'], unique=False)
    op.create_index(op.f('ix_fraud_predictions_model_registry_id'), 'fraud_predictions', ['model_registry_id'], unique=False)
    op.create_index(op.f('ix_fraud_predictions_model_version'), 'fraud_predictions', ['model_version'], unique=False)
    op.create_index(op.f('ix_fraud_predictions_risk_score'), 'fraud_predictions', ['risk_score'], unique=False)
    op.create_index(op.f('ix_fraud_predictions_transaction_id'), 'fraud_predictions', ['transaction_id'], unique=True)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=True, comment='NULL = broadcast to all users'),
    sa.Column('related_transaction_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('high_risk_alert', 'blocked_transaction', 'review_required', 'model_update', 'system', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['related_transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_related_transaction_id'), 'notifications', ['related_transaction_id'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_is_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('review_queue',
    sa.Column('fraud_prediction_id', sa.UUID(), nullable=False),
    sa.Column('assigned_analyst_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_review', 'resolved', name='review_status'), nullable=False),
    sa.Column('analyst_decision', sa.Enum('fraud', 'legitimate', name='analyst_decision'), nullable=True, comment='Ground truth captured for future model retraining'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_analyst_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fraud_prediction_id'], ['fraud_predictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_queue_assigned_analyst_id'), 'review_queue', ['assigned_analyst_id'], unique=False)
    op.create_index(op.f('ix_review_queue_created_at'), 'review_queue', ['created_at'], unique=False)
    op.create_index(op.f('ix_review_queue_fraud_prediction_id'), 'review_queue', ['fraud_prediction_id'], unique=True)
    op.create_index(op.f('ix_review_queue_id'), 'review_queue', ['id'], unique=False)
    op.create_index(op.f('ix_review_queue_status'), 'review_queue', ['status'], unique=False)
    op.create_index('ix_review_queue_status_created_at', 'review_queue', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_review_queue_status_created_at', table_name='review_queue')
    op.drop_index(op.f('ix_review_queue_status'), table_name='review_queue')
    op.drop_index(op.f('ix_review_queue_id'), table_name='review_queue')
    op.drop_index(op.f('ix_review_queue_fraud_prediction_id'), table_name='review_queue')
    op.drop_index(op.f('ix_review_queue_created_at'), table_name='review_queue')
    op.drop_index(op.f('ix_review_queue_assigned_analyst_id'), table_name='review_queue')
    op.drop_table('review_queue')
    op.drop_index('ix_notifications_user_is_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_related_transaction_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_fraud_predictions_transaction_id'), table_name='fraud_predictions')
    op.drop_index(op.f('ix_fraud_predictions_risk_score'), table_name='fraud_predictions')
    op.drop_index(op.f('ix_fraud_predictions_model_version'), table_name='fraud_predictions')
    op.drop_index(op.f('ix_fraud_predictions_model_registry_id'), table_name='fraud_predictions')
    op.drop_index(op.f('ix_fraud_predictions_is_fraud'), table_name='fraud_predictions')
    op.drop_index(op.f('ix_fraud_predictions_id'), table_name='fraud_predictions')
    op.drop_index('ix_fraud_predictions_decision_created_at', table_name='fraud_predictions')
    op.drop_index(op.f('ix_fraud_predictions_decision'), table_name='fraud_predictions')
    op.drop_index(op.f('ix_fraud_predictions_created_at'), table_name='fraud_predictions')
    op.drop_table('fraud_predictions')
    op.drop_index('ix_fraud_logs_transaction_stage', table_name='fraud_logs')
    op.drop_index(op.f('ix_fraud_logs_transaction_id'), table_name='fraud_logs')
    op.drop_index(op.f('ix_fraud_logs_status'), table_name='fraud_logs')
    op.drop_index(op.f('ix_fraud_logs_id'), table_name='fraud_logs')
    op.drop_index(op.f('ix_fraud_logs_created_at'), table_name='fraud_logs')
    op.drop_table('fraud_logs')
    op.drop_index(op.f('ix_transactions_submitted_by_id'), table_name='transactions')
    op.drop_index('ix_transactions_merchant_created_at', table_name='transactions')
    op.drop_index(op.f('ix_transactions_merchant'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_customer_reference'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_amount'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_model_metrics_recorded_at'), table_name='model_metrics')
    op.drop_index(op.f('ix_model_metrics_model_registry_id'), table_name='model_metrics')
    op.drop_index('ix_model_metrics_model_recorded_at', table_name='model_metrics')
    op.drop_index(op.f('ix_model_metrics_id'), table_name='model_metrics')
    op.drop_index(op.f('ix_model_metrics_created_at'), table_name='model_metrics')
    op.drop_table('model_metrics')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_user_created_at', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_endpoint'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_model_registry_version'), table_name='model_registry')
    op.drop_index(op.f('ix_model_registry_status'), table_name='model_registry')
    op.drop_index('ix_model_registry_single_active', table_name='model_registry', postgresql_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_model_registry_id'), table_name='model_registry')
    op.drop_index(op.f('ix_model_registry_created_at'), table_name='model_registry')
    op.drop_table('model_registry')
    # ### end Alembic commands ###
